import localFont   from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import * as React from 'react'

// 1. import `ChakraProvider` component
import { ChakraProvider } from '@chakra-ui/react'


function App({ children }) {
  // 2. Wrap ChakraProvider at the root of your app
  return (
    <html style={{visibility: "hidden", backgroundColor: "white"}}>
      <body style={{width: "100vw", height: "100vh"}}>
        <ChakraProvider>
          {children}
        </ChakraProvider>
      </body>
    </html>
   
  )
}

export default App;